version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres-db"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=grupo_boticario
    ports:
      - "5432:5432"
    volumes:
      - ./__data__:/var/lib/postgresql/data
