name: Grupo Boticario - Application tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: mongo-install, npm install, build, and test
      run: |
        sudo docker run --name mongo -d -p 27017:27017 mongo
        npm i
        npm run build --if-present
        npm run test:all
      env:
        CI: true
        MONGO_URI: mongodb://127.0.0.1:27017/grupo_boticario
        PORT: 3000
